## Learn Scikit-Learn

### supervised learning
* Collect Training Data -> Train Classifier -> Make Predictions

* many kinds of classifiers
    * Artificial neural network
    * Support Vector Machine
    * etc

### Training Data

| Weight | Texture | Label |
| --- | --- | --- |
| 150g | Bumpy | Orage |
| 170g | Bumpy | Orage |
| 140g | Smooth | Apple |
| 130g | Smooth | Apple |

* the whole table is our training data
* **features**: Weight, Texture
* **examples**: each row of the table

In [8]:
from sklearn import tree

# collect training data
textureNames = {0: 'Bumpy', 1:'Smooth'}
labelNames = {0: 'Apple', 1: 'Orange'}
features = [[150, 0], [170, 0], [140, 1], [130, 1]]
lables = [1,1,0,0]

# training classifier
clf = tree.DecisionTreeClassifier()
clf = clf.fit(features, lables)

# make predictions
print(clf.predict([[150,0]]))

[1]


## have a try with Iris data

In [16]:
from sklearn.datasets import load_iris

iris = load_iris()
print(iris.feature_names)
print(iris.target_names)
print(iris.data[0])
print(iris.target[0])

['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']
['setosa' 'versicolor' 'virginica']
[5.1 3.5 1.4 0.2]
0


In [20]:
import numpy as np
from sklearn.datasets import load_iris

iris = load_iris()
test_idx = [0, 50, 100] #select 3 samples as test data

# training data
train_target = np.delete(iris.target, test_idx)
train_data = np.delete(iris.data, test_idx, axis=0)

# testing data
test_target = iris.target[test_idx]
test_data = iris.data[test_idx]

# training classifier
clf = tree.DecisionTreeClassifier()
clf = clf.fit(train_data, train_target)

# make predictions
print(test_target)
print(clf.predict(test_data))

[0 1 2]
[0 1 2]


### what makes a good feature?